### ISSUE TITLE
Add "squatted after 1960" in legend

### ISSUE THREAD

**Issue by remmap** [eikes/sqek#11]
There are squats in NL and UK from the 1960s, for example:
http://maps.squat.net/en/cities/amsterdam/squats/#general-vetterstraat

At the moment this squat is giving a broken image, presumably because there is no colour set for after 1960 in the legend.

**Comment by eikes** [comment]
Resolved in 383952f70168ee3157b82e316d3031b359c33f3c

**Comment by remmap** [comment]
thanks!
