### ISSUE TITLE
Add introduction to Brighton map

### ISSUE THREAD

**Issue by remmap** [eikes/sqek#12]
The introduction could be a tab in the top right menu bar. The text could be adapted for other cities if necessary.

Suggested text:

This map is based mainly on a database of social centres in Brighton (1960s until end 2013) which is hosted online at http://sqek.squat.net/database/.

The database was compiled from a range of sources which included the Brighton Voice newspaper, the Brighton Argus newspaper, the SchNews newsletter, participant observation, internet research about individual projects, informal conversations with squatters past and present, and academic articles.

The map makes no claim to be definitive or hegemonic (nor should it). Obviously, the majority of squats are residential and silent, whereas the projects profiled here had a public presence, demonstrated by events which were welcome to all.

If you would like to add more places or corrections, please do! There is a form below to enter info. Please note for a project to be listed the minimum requirements would be address / (approximate) start date / (approximate) end date. Please put additions or corrections for existing projects in the text box.

[FORM]

**Comment by remmap** [comment]
FORM = https://github.com/eikes/sqek/issues/8

**Comment by eikes** [comment]
You can now write a text about the city using the "update city" link in the menu. The text will appear in the sidebar when you click on the city name in the menubar on the right side.
