### ISSUE TITLE
Add analysis text to Brighton map

### ISSUE THREAD

**Issue by remmap** [eikes/sqek#13]
I would like to add the article I have written about the Brighton database to the Brighton map. 

It's online here http://www.socresonline.org.uk/19/4/6.html but seems to be restricted access.

I have it as pdf or odt, at the moment it contains images but I could make an image-version.

**Comment by eikes** [comment]
You can now write a text about the city using the "update city" link in the menu. The text will appear in the sidebar when you click on the city name in the menubar on the right side.

**Comment by eikes** [comment]
PS: The sqek map is not content management system for any content. I think that a text like this should be hosted somewhere else as it really is not in the scope of the map to host PDFs or custom complex html pages. You can of course add a link to the city description / body.
