### ISSUE TITLE
Language functionality

### ISSUE THREAD

**Issue by remmap** [eikes/sqek#15]
if the maps feature cities from different places in europe, we should have those different langauges represented

this wouldn't be too much work for the contributors to translate the tabs

better to do this when all the tabs are set up

**Comment by eikes** [comment]
The functionality is already there. If you provide me with, for example, a dutch translation of this file:

https://github.com/eikes/sqek/blob/master/config/locales/de.yml

I can add dutch as a language. Same goes for spanish etc.
