### ISSUE TITLE
Add contact  form

### ISSUE THREAD

**Issue by remmap** [eikes/sqek#8]
A contact form would be a way for people who want to contribute to the map to access the person maintaining it.

It could require data to be added for: address / (approximate) date of squat / (approximate) date of eviction (or ongoing) so as to ensure the data is useful. it could also have a text box for any other comments, links and additions/corrections to previously published projects.

**Comment by remmap** [comment]
Also it would be good to ask for a source for information/fotos

**Comment by eikes** [comment]
Depends on https://github.com/eikes/sqek/issues/18

**Comment by eikes** [comment]
Comments can now be added to cities and squats.
